int - int(input())
float - float(input())
str- input()
list of str - input().split()
tuple of str -  tuple(input().split())
set of str - set(input().split())
list of int- list(map(input().split()))
tuple of int - tuple(map(input().split()))
set of int- set(map(input().split()))
list of float- list(map(input().split()))
tuple of float - tuple(map(input().split()))
set of float- set(map(input().split()))
